### ISSUE TITLE
Cannot click or drag on the top 1 pixel of the title bar when maximizing the window

### ISSUE THREAD

**Issue by CodingOctocat** [Simnico99/MicaWPF#20]
**Describe the bug**
Cannot click or drag on the top 1 pixel of the title bar when maximizing the window

**To Reproduce**
1. Maximize window
2. Move mouse pointer to top window
3. Try right click or drag the window
4. Can not open RightContextMenu or Drag the window

**Screenshots**
The red dot position cannot trigger the mouse event.
![Snipaste_2022-06-28_10-06-41](https://user-images.githubusercontent.com/7220248/176076375-89b8d369-50ba-4b84-92ad-c802595b37a9.png)

**Desktop (please complete the following information):**
- OS Version:
  > 版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎11/‎7 ‎星期日
操作系统版本	22000.739
体验	Windows 功能体验包 1000.22000.739.0

 - .Net Version 6.06

**Comment by Simnico99** [comment]
I will take a look.

**Comment by Simnico99** [comment]
Found the issue working on a fix.

**Comment by Simnico99** [comment]
The issue was caused by the ReziseBorderThickness staying 8 when the window was maximized preventing mouse events.
The issue should be fixed in the version 3.1.28. (Pushing the version right now.)
![image](https://user-images.githubusercontent.com/80013536/176082562-affcc3e0-7a15-457a-aeed-860da5d848d9.png)

I will be awaiting your confirmation.

**Comment by CodingOctocat** [comment]
v3.1.28 work fine.
Thanks.
