### ISSUE TITLE
Applying Mica effect to ComboBox, Menu and ContextMenuFeature Request

### ISSUE THREAD

**Issue by MajorXAML** [Simnico99/MicaWPF#28]
Hello @Simnico99 
Thanks for the library, do you think it's possible to apply the Mica effect to these controls?
As far as I understand, these controls exist outside the main window, so the mica effect does not apply to them and it doesn't look pretty 
![image_2022-10-03_183632650](https://user-images.githubusercontent.com/93913816/193618338-b2d965e2-292c-47e9-92ac-3fa3547d990a.png)

**Comment by Simnico99** [comment]
Well this one is a complex one technically it is a Control and not a separate windows the Ultimate goal would be to try implementing an Acrylic brush myself to replicate the exact behavior of WinUI but transparency with blur doesn't works well in WPF. I've tried implementing something similar to what is used in SourceCor FluentWPF but the issue is with his brush you need an opaque background which would hide the Mica effect on the Window, I will try to come up with something but any help would be greatly appreciated.

**Comment by Simnico99** [comment]
I will take a look as soon as I can when I implemented myself I had to put a an opaque background

**Comment by Simnico99** [comment]
After taking a look and deconstructing the way it works its using the background control to generate de blur because of the way WPF works it has to have a layer behind the controls in order to generate a blur in front of it. If you try it with the opacity of the background control set to 0 the blur is absent. Which is kind of an issue as I can't have a grid that span the entire windows or it will hide the Mica or Acrylic of the current window.

**Comment by Simnico99** [comment]
As it seems to be a limitation caused by the way WPF renders I cannot implement this.
